module.exports = {

    balanceTypes: {
        1: "General Cash",
        2: "Promotional Cash",
        3: "Bad Pin",
        4: "Monthly Exp",
        5: "Yearly Exp",
        6: "Free SMS",
        7: "Wallet Exp",
        8: "_WLC_Service",
        9: "Data",
        21: "General Cash",
        22: "Promotional Cash",
        23: "Bad Pin",
        24: "Monthly Exp",
        25: "Yearly Exp",
        26: "Free SMS",
        27: "Wallet Exp",
        28: "_WLC_Service",
        29: "Data",
        30: "Promotional Data",
        31: "PAYG",
        32: "CTAllowLastDate",
        33: "QuotaLimit-M1",
        34: "QuotaLimit-M2",
        35: "QuotaLimit-M3",
        36: "QuotaLimit-M4",
        37: "QuotaLimit-M5",
        38: "QuotaLimit-M6",
        39: "QuotaLimit-M7",
        40: "QuotaLimit-M8",
        41: "QuotaLimit-M9",
        42: "QuotaLimit-ALL",
        61: "Gift Data",
        81: "Notification Slab",
        101: "Autorecovery",
        105: "FDFL Count",
        106: "FDFL Flag",
        107: "FDFL Data",
        108: "Tablet Data",
        122: "FDFL2 Count",
        142: "TerminatePC Count",
        162: "Reset Count",
        163: "ULNitePlan Status",
        182: "Staff Data",
        222: "Bonus Data",
        242: "Reward_slab Count",
        243: "Reward_slab1 Count",
        262: "5GB_Winback Count",
        263: "10GB_Winback Count",
        264: "20GB_Winback Count",
        282: "Gift Count",
        303: "ULDayNitePlan Data",
        304: "ULDayNitePlan Status",
        323: "DataPurchases Count",
        342: "Videobundle Data",
        343: "Surfplus Count",
        402: "WinbackTrack Count",
        403: "WinbackTop-up Count",
        442: "WinbackGift Count",
        462: "ULBusiness2 Data",
        463: "ULBusiness2 Status",
        464: "TrackingPCBusiness Count",
        482: "SetPCStatus Count",
        483: "TerminateBusPC Count",
        509: "TrackingBusiinessPC Count",
        522: "Business2 Count",
        562: "Expenditure Count",
        582: "GiftTrack Count",
        602: "TV_Unlimited Status",
        622: "FreeWknd Status",
        642: "SamsungTag",
        643: "Expenditure2 Count",
        662: "Complimentary Data",
        682: "ULVideo Data",
        683: "ULVideo Status",
        722: "WBTracknew2 Count",
        742: "Ten4Ten Data",
        762: "WinbackTracknew2 Count",
        782: "SimOnlyBndle Count",
        802: "FreeTime Data",
        822: "10GBVideo Data",
        823: "20GBVideo Data",
        842: "3months Count",
        862: "1GBSurfplus Data",
        863: "1.6GBSurfplus Data",
        864: "7GBSurfplus Data",
        865: "2GBSurfplus Data",
        866: "3.2GBSurfplus Data",
        867: "5GBSurfplus Data",
        868: "12GBSurfplus Data",
        869: "30GBSurfplus Data",
        870: "45GBSurfplus Data",
        871: "65GBSurfplus Data",
        872: "125GBSurfplus Data",
        873: "185GBSurfplus Data",
        874: "Surfplus_new Count",
        875: "SaturdayVibe Count",
        876: "Free Saturday Data",
        877: "TrackMultipleExpiry Count",
        922: "Winback_3monthsTrack Count",
        923: "Winback_SundayStatus Count",
        942: "Taxify Data",
        943: "Taxify Status",
        944: "AftownMusic Data",
        982: "ExtraTime Track Count",
        983: "ExtraTime Bonus Data",
        1002: "Anniversary Data",
        1003: "NewWinbackTrack Count",
        1004: "UL_AlwaysON_Standard Status",
        1005: "UL_AlwaysON_Standard Data",
        1006: "UL_AlwaysON_Super Status",
        1007: "UL_AlwaysON_Super Data",
        1008: "UL_AlwaysON_Ultra Status",
        1009: "UL_AlwaysON_Ultra Data",
        1022: "Activate_AlwaysON Count",
        1023: "Activate_Super Count",
        1024: "Activate_Ultra Count",
        1042: "UL_AlwaysON_Starter Data",
        1043: "UL_AlwaysON_Starter Status",
        1044: "UL_AlwaysON_Lite Data",
        1045: "UL_AlwaysON_Lite Status",
        1046: "UL_AlwaysON_Streamer Data",
        1047: "UL_AlwaysON_Streamer Status",
        1062: "GracePeriod Status",
        1082: "Staff_AlwaysON_1GB Data",
        1083: "Staff_AlwaysON_1GB Count",
        1084: "Staff_AlwaysON_2GB Data",
        1085: "Staff_AlwaysON_2GB Count",
        1086: "Staff_AlwaysON_5GB Data",
        1087: "Staff_AlwaysON_5GB Count",
        1088: "Staff_AlwaysON_10GB Data",
        1089: "Staff_AlwaysON_10GB Count",
        1090: "Staff_AlwaysON_3GB Count",
        1091: "Staff_AlwaysON_3GB Data",
        1102: "Bundle ExpiryTrack Status",
        1142: "Lite Boost Ext",
        1143: "Activate_Unlimited Count",
        1162: "SetPromoExtensionTag  Count",
        1182: "Test Drive Data",
        1183: "Test Drive Track Count",
        1184: "UL_AlwaysON_Maxi Data",
        1185: "UL_AlwaysON_Maxi Status",
        1186: "MGMRferredBonusTrack Count",
        1187: "MGMRferralBonusTrack Count",
        1202: "internalBdlId Count",
        1203: "Free Cash",
        1204: "bdlPurchaseCounter Count",
        1242: "Pay Weekly Data",
        1270: "BingeXtra Data",
        1271: "Zoom Data",
        1272: "WorkStreak Data",
        1273: "AfterHours Status",
        1274: "AfterHoursTemp Status",
        1282: "UL_AlwaysON_OneYear Data",
        1283: "UL_AlwaysON_OneYear Status",
        1284: "TaxifyUL_Lite Status",
        1285: "TaxifyUL_Lite Data",
        1286: "TaxifyUL_Super Data",
        1287: "TaxifyUL_Super Status",
        1302: "SanBraFie Data",
        1322:"No_Zero_Rate Count",
        1323:"ExtensionUnlimited Status"


    },

    balanceTypesArrays: [
        'Autorecovery',
        'Bundle ExpiryTrack Status',
        'Surfplus Count',
        'Data',
        'Promotional Data',
        'Gift Data',
        'FDFL Data',
        'Bonus Data',
        'Ten4Ten Data',
        '1.6GBSurfplus Data',
        '3.2GBSurfplus Data',
        '5GBSurfplus Data',
        '7GBSurfplus Data',
        '12GBSurfplus Data',
        '30GBSurfplus Data',
        '45GBSurfplus Data',
        '65GBSurfplus Data',
        '125GBSurfplus Data',
        '185GBSurfplus Data',
        'BingeXtra Data',
        'Zoom Data',
        'WorkStreak Data',
        'AfterHours Status',
        'Free Saturday Data',
        'Pay Weekly Data',
        'Taxify Data',
        'ExtraTime Bonus Data',
        'GracePeriod Status',
        'UL_AlwaysON_OneYear Data',
        'UL_AlwaysON_OneYear Status',
        'TaxifyUL_Lite Status',
        'TaxifyUL_Lite Data',
        'TaxifyUL_Super Data',
        'TaxifyUL_Super Status',
        'SanBraFie Data',
        'ULBusiness2 Data',
        'ULBusiness2 Status',
        'ULNitePlan Status',
        'ULDayNitePlan Data',
        'ULDayNitePlan Status',
        'UL_AlwaysON_Standard Status',
        'UL_AlwaysON_Standard Data',
        'UL_AlwaysON_Super Status',
        'UL_AlwaysON_Super Data',
        'UL_AlwaysON_Ultra Status',
        'UL_AlwaysON_Ultra Data',
        'UL_AlwaysON_Starter Data',
        'UL_AlwaysON_Starter Status',
        'UL_AlwaysON_Lite Data',
        'UL_AlwaysON_Lite Status',
        'UL_AlwaysON_Streamer Data',
        'UL_AlwaysON_Streamer Status',
        'UL_AlwaysON_Maxi Data',
        'UL_AlwaysON_Maxi Status',
        'Staff_AlwaysON_1GB Data',
        'Staff_AlwaysON_2GB Data',
        'Staff_AlwaysON_5GB Data',
        'Staff_AlwaysON_10GB Data',
        'Staff_AlwaysON_3GB Data',
        'No_Zero_Rate Count',
        'ExtensionUnlimited Status'
    ]

    ,
    productTypes: [
        'Individual',
        'NewPrepaidOffer',
        'RideON',
        'SME',
        'SME/SOHO',
        'Student',
        'SurfStaff',
        'Taxify PT',
        'Always ON Business',
        'Always ON Group',
        'Business Corporate',
        'Pay Weekly',
        'Test Drive',
        'Business Individual'
    ],

    unlimitedBundles: {
        'Unlimited Day/Night': {
            data_balanceType: 'ULDayNitePlan Data',
            status_balanceType: 'ULDayNitePlan Status',
            dataValue: 272629760,
            id: 21,
            validity: 30
        },
        'AlwaysON Standard': {
            data_balanceType: 'UL_AlwaysON_Standard Data',
            status_balanceType: 'UL_AlwaysON_Standard Status',
            dataValue: 15728640,
            id: 30,
            validity: 30
        },
        'AlwaysON Super': {
            data_balanceType: 'UL_AlwaysON_Super Data',
            status_balanceType: 'UL_AlwaysON_Super Status',
            dataValue: 22722642,
            id: 32,
            validity: 30
        },
        'AlwaysON Ultra': {
            data_balanceType: 'UL_AlwaysON_Ultra Data',
            status_balanceType: 'UL_AlwaysON_Ultra Status',
            dataValue: 31457280,
            id: 33,
            validity: 30
        },
        'AlwaysON Group Lite': {
            data_balanceType: 'UL_AlwaysON_Lite Data',
            status_balanceType: 'UL_AlwaysON_Lite Status',
            dataValue: 3355443,
            id: 36,
            validity: 30
        },
        'AlwaysON Group Starter': {
            data_balanceType: 'UL_AlwaysON_Starter Data',
            status_balanceType: 'UL_AlwaysON_Starter Status',
            dataValue: 1258291,
            id: 34,
            validity: 30
        },
        'AlwaysON Group Streamer': {
            data_balanceType: 'UL_AlwaysON_Streamer Data',
            status_balanceType: 'UL_AlwaysON_Streamer Status',
            dataValue: 5452595,
            id: 35,
            validity: 30
        },
        'AlwaysON Group Maxi': {
            data_balanceType: 'UL_AlwaysON_Maxi Data',
            status_balanceType: 'UL_AlwaysON_Maxi Status',
            dataValue: 9017753,
            id: 37,
            validity: 30
        },
        'SME Standard': {
            data_balanceType: 'UL_AlwaysON_Standard Data',
            status_balanceType: 'UL_AlwaysON_Standard Status',
            dataValue: 13107200,
            id: 41,
            validity: 30
        },
        'SME Super': {
            data_balanceType: 'UL_AlwaysON_Super Data',
            status_balanceType: 'UL_AlwaysON_Super Status',
            dataValue: 18350080,
            id: 43,
            validity: 30
        },
        'SME Ultra': {
            data_balanceType: 'UL_AlwaysON_Ultra Data',
            status_balanceType: 'UL_AlwaysON_Ultra Status',
            dataValue: 24463278,
            id: 44,
            validity: 30
        },
        'SME Lite': {
            data_balanceType: 'UL_AlwaysON_Lite Data',
            status_balanceType: 'UL_AlwaysON_Lite Status',
            dataValue: 6291456,
            id: 40,
            validity: 30
        },
        'SME Starter': {
            data_balanceType: 'UL_AlwaysON_Starter Data',
            status_balanceType: 'UL_AlwaysON_Starter Status',
            dataValue: 4194304,
            id: 42,
            validity: 30

        },
        'SME Maxi': {
            data_balanceType: 'UL_AlwaysON_Maxi Data',
            status_balanceType: 'UL_AlwaysON_Maxi Status',
            dataValue: 9017753,
            id: 45,
            validity: 30
        },
        'Taxify Super': {
            data_balanceType: 'TaxifyUL_Super Data',
            status_balanceType: 'TaxifyUL_Super Status',
            dataValue: 5452595,
            id: 61,
            validity: 30
        },
        'Taxify Lite': {
            data_balanceType: 'TaxifyUL_Lite Data',
            status_balanceType: 'TaxifyUL_Lite Status',
            dataValue: 3355443,
            id: 60,
            validity: 7
        },
        'RideON': {
            data_balanceType: 'Taxify Data',
            status_balanceType: 'Taxify Status',
            dataValue: 31457280,
            id: 51,
            validity: 30
        },
        'RideON Lite': {
            data_balanceType: 'Taxify Data',
            status_balanceType: 'Taxify Status',
            dataValue: 31457280,
            id: 50,
            validity: 7
        },

    }


}
